events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('list/', views.event_list, name='event_list'),
    path('detail/<int:pk>/', views.event_detail, name='event_detail')
]

realworlddjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('events/', include('events.urls')),
]

urlpatterns += [
    path('api/events/', include('events.urls_api'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=90, default='', verbose_name='Категория')

    def display_event_count(self):
        return self.events.count()

    display_event_count.short_description = 'Количество событий'

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Feature(models.Model):
    title = models.CharField(max_length=90, default='', verbose_name='Свойство')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Свойство события'
        verbose_name_plural = 'Свойства события'


class Event(models.Model):
    FULLNESS_FREE = '1'
    FULLNESS_MIDDLE = '2'
    FULLNESS_FULL = '3'
    FULLNESS_LEGEND_FREE = '<= 50%'
    FULLNESS_LEGEND_MIDDLE = '> 50%'
    FULLNESS_LEGEND_FULL = 'sold-out'
    FULLNESS_VARIANTS = (
        (FULLNESS_FREE, FULLNESS_LEGEND_FREE),
        (FULLNESS_MIDDLE, FULLNESS_LEGEND_MIDDLE),
        (FULLNESS_FULL, FULLNESS_LEGEND_FULL),
    )

    logo = models.ImageField(upload_to='events/events/', blank=True, null=True)
    title = models.CharField(max_length=200, default='', verbose_name='Название')
    description = models.TextField(default='', verbose_name='Описание')
    date_start = models.DateTimeField(verbose_name='Дата начала')
    participants_number = models.PositiveSmallIntegerField(default=0, verbose_name='Количество участников')
    is_private = models.BooleanField(default=False, verbose_name='Частное')
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE, related_name='events')
    features = models.ManyToManyField(Feature, blank=True)

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'

    @property
    def rate(self):
        all_reviews = self.reviews.count()
        sum_rate = sum([i.rate for i in self.reviews.all()])
        try:
            return round(sum_rate / all_reviews, 1)
        except:
            return 0

    @property
    def logo_url(self):
        return self.logo.url if self.logo else f'{settings.STATIC_URL}images/svg-icon/event.svg'

    def get_absolute_url(self):
        return reverse('events:event_detail', args=[str(self.pk)])

    def __str__(self):
        return self.title

    def get_enroll_count(self):
        """
        Return number of enrolls for this event.
        """
        return self.enrolls.count()

    def get_places_left(self):
        """
        Return number of free places for this event.
        """
        return int(self.participants_number or 0) - self.get_enroll_count()

    def get_fullness_legend(self, **kwargs):
        """
        Return legend for event's places_left.
        Legend is in the FULLNESS_VARIANTS.

        kwargs may contain the following parameters:
        `places_left`: number of free places for this event (to avoid additional query)
        """
        legend = ''
        if int(self.participants_number or 0) > 0:
            legend = Event.FULLNESS_LEGEND_FREE
            places_left = kwargs.get('places_left', None)
            if places_left is None:
                places_left = self.get_places_left()
            if places_left == 0:
                legend = Event.FULLNESS_LEGEND_FULL
            elif places_left < self.participants_number / 2:
                legend = Event.FULLNESS_LEGEND_MIDDLE
        return legend

    def display_enroll_count(self):
        return self.get_enroll_count()

    display_enroll_count.short_description = 'Количество записей'

    def display_places_left(self):
        places_left = self.get_places_left()
        return f'{places_left} ({self.get_fullness_legend(places_left=places_left)})'

    display_places_left.short_description = 'Осталось мест'


class Enroll(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='enrolls')
    event = models.ForeignKey(Event, null=True, on_delete=models.CASCADE, related_name='enrolls')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.event.title} - {self.user}'

    class Meta:
        verbose_name = 'Запись на событие'
        verbose_name_plural = 'Записи на событие'


class Review(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='reviews')
    event = models.ForeignKey(Event, null=True, on_delete=models.CASCADE, related_name='reviews')
    rate = models.PositiveSmallIntegerField(default=0)
    text = models.TextField(max_length=1000, default='')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.rate} - {self.event.title}'

    class Meta:
        verbose_name = 'Отзыв на событие'
        verbose_name_plural = 'Отзывы на события'

events/views.py
import datetime

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from events.models import Category, Feature, Event, Review
from django.views.decorators.http import require_POST


def event_list(request):
    template_name = 'events/event_list.html'
    category_objects = Category.objects.all()
    features_objects = Feature.objects.all()
    event_objects = Event.objects.all()

    context = {
        'category_objects': category_objects,
        'feature_objects': features_objects,
        'event_objects': event_objects,
    }

    return render(request, template_name, context)


def event_detail(request, pk):
    template_name = 'events/event_detail.html'
    event = get_object_or_404(Event, pk=pk)
    context = {
        'event': event,
    }

    return render(request, template_name, context)


@require_POST
def create_review(request):

    data = {
        'ok': True,
        'msg': '',
        'rate': request.POST.get('rate'),
        'text': request.POST.get('text'),
        'created': datetime.date.today().strftime('%d.%m.%Y'),
        'user_name': ''
    }

    messages = {
        'is_not_registered': 'Отзывы могут оставлять только зарегистрированные пользователи',
        'is_not_rated_or_texted':'Оценка и текст отзыва - обязательные поля',
        'is_reviewed': 'Вы уже оставляли отзыв к этому событию',
        'is_empty': 'Такого события не существует',
    }

    pk = request.POST.get('event_id', '')
    rate = request.POST.get('rate', '')
    text = request.POST.get('text', '')

    if not pk:
        data['msg'] = messages['is_empty']
        data['ok'] = False
        return JsonResponse(data)
    else:

        event = Event.objects.get(pk=pk)

        if not request.user.is_authenticated:
            data['msg'] = messages['is_not_registered']
            data['ok'] = False
            return JsonResponse(data)

        data['user_name'] = request.user.__str__()

        if not rate or not text:
            data['msg'] = messages['is_not_rated_or_texted']
            data['ok'] = False
            return JsonResponse(data)

        elif Review.objects.filter(user=request.user, event=event).exists():
            data['msg'] = messages['is_reviewed']
            data['ok'] = False
            return JsonResponse(data)

        else:
            new_review = Review(
                user=request.user,
                event=event,
                rate=data['rate'],
                text=data['text'],
                created=data['created'],
                updated=data['created']
            )

            new_review.save()
            return JsonResponse(data)

events/templates/events/event_list.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Real World Django - События</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!-- Project style -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>

<div class="vertical-layout">

    <!-- Start LEFT_MENU -->
    <div class="leftbar">
        <div class="logobar">
            <a href="index.html" class="logo logo-large">
                <img src="{% static 'images/svg-icon/logo.svg'%}" alt="logo" style="height: 40px">
            </a>
        </div>
        <ul class="vertical-menu" id="vertical-menu">
            <li class="vertical-menu-item">
                <span>Главное</span>
                <ul class="vertical-submenu">
                    <li><a href="event_list.html">События</a></li>
                    <li><a href="mail.html">Подписчики</a></li>
                </ul>
            </li>
            <li class="vertical-menu-item">
                <span>Аккаунт</span>
                <ul class="vertical-submenu">
                    <li><a href="profile.html">Мой аккаунт</a></li>
                    <li><a href="#">Изменить пароль</a></li>
                    <li><a href="#">Сбросить пароль</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- menu for mobile -->
    <div class="topbar-mobile">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="mobile-logobar" style="max-width: 40px">
                    <a href="#" class="mobile-logo">
                        <img src="{% static 'images/svg-icon/logo.svg'%}" class="img-fluid" alt="logo">
                    </a>
                </div>
                <div class="mobile-togglebar">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <div class="menubar">
                                <a class="menu-hamburger" href="#" id="menu-hamburger">
                                    <img src="{% static 'images/svg-icon/collapse.svg'%}"
                                         class="img-fluid menu-hamburger-collapse"
                                         alt="collapse">
                                    <img src="{% static 'images/svg-icon/close.svg'%}"
                                         class="img-fluid menu-hamburger-close"
                                         alt="close">
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="d-md-none" style="height: 90px"></div>
    <!-- End LEFT_MENU -->

    <!-- Start MAIN_CONTAINER -->
    <div class="rightbar">

        <!-- Start TOP_BAR -->
        <div class="container-fluid bg-white py-3">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto text-center ms-4">
                    <h4>События</h4>
                </div>
                <div class="col-auto text-center me-4">
                    {% if request.user and request.user.is_authenticated %}
                        <a href="#" class="btn btn-outline-primary">+ Добавить событие</a>
                    {% else %}
                        <a href="#" class="btn btn-outline-primary">Войти</a>
                        <a href="#" class="btn btn-primary">Регистрация</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- End TOP_BAR -->

        <!-- Start CONTAINER_BAR -->
        <div class="container-fluid mt-3">
            <div class="row mb-4">
                <div class="col">
                    <div class="card shadow">
                        <div class="card-body">
                            <form>
                                <div class="row row-cols-lg-auto g-3 align-items-start">
                                    <div class="col-12">
                                        <label for="category" class="form-label">Категория:</label>
                                        <select class="form-select" id="category">
                                            <option selected="">---------</option>
                                            {% for category in category_objects %}
                                                <option value="{{ forloop.counter }}">{{ category.title }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-12">
                                        <label for="features" class="form-label">Свойства:</label>
                                        <select class="form-select" multiple="" id="features">
                                            {% for feature in feature_objects %}
                                                <option value="{{ forloop.counter }}">{{ feature.title }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-12 d-md-flex">
                                        <div class="mx-1">
                                            <label for="id_date_start" class="form-label">Дата начала:</label>
                                            <input type="date" class="form-control" id="id_date_start">
                                        </div>
                                        <div class="mx-1">
                                            <label for="id_date_end" class="form-label">Дата окончания:</label>
                                            <input type="date" class="form-control" id="id_date_end">
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-3">
                                    <div class="col-12 d-md-flex">
                                        <div class="form-check me-3">
                                            <input class="form-check-input" type="checkbox" value="" id="is_private">
                                            <label class="form-check-label" for="is_private">
                                                Приватное
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="is_available">
                                            <label class="form-check-label" for="is_available">
                                                Есть места
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-12 mt-3">
                                        <button type="submit" class="btn btn-primary">Фильтровать</button>
                                        <button type="submit" class="btn btn-outline-danger">Сбросить</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#" data-test="p_start">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_previous">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_1">1</a></li>
                <li class="page-item active"><a class="page-link" href="#" data-test="p_2">2</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_3">3</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_next">Next</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_end">&raquo;</a></li>
            </ul>
            <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 row-cols-xxl-4 g-4">

                {% for event in event_objects %}

                    <div class="col">
                        <div class="card h-100">
                            <div class="card-header">
                                <h5 class="card-title mb-0">{{ event.title }}</h5>
                                {% if event.is_private %}
                                    <span data-test="is_private" class="badge bg-dark">Private</span>
                                {% endif %}
                            </div>
                            <div class="card-body">
                                <h3>{{event.display_enroll_count}} из {{ event.participants_number }}</h3>
                                <p>участников</p>
                                <ul class="py-2">
                                    {% for feature in event.features.all %}
                                        <li>{{feature}}</li>
                                    {% endfor %}
                                </ul>
                                <p>
                                    дата: <strong data-test="date_start">{{event.date_start|date:"d.m.Y"}} в {{event.date_start|date:"H:i"}}</strong>
                                </p>
                            </div>
                            <div class="card-footer">
                                <a href="{{event.get_absolute_url}}" class="btn btn-success">Смотреть</a>
                                <a href="event_update.html" class="btn btn-outline-primary" title="Изменить">
                                    <i class="bi bi-pencil-square"></i>Изменить
                                </a>
                            </div>
                        </div>
                    </div>

                {% endfor %}


        <!-- End CONTAINER_BAR -->

        <!-- Start FOOTER -->
        <div style="height: 70px"></div>
        <div class="footerbar">
            <footer class="footer">
                <p class="mb-0">© Pumpskill. Real World Django</p>
            </footer>
        </div>
        <!-- End FOOTER -->

    </div>
    <!-- End MAIN_CONTAINER -->

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
<script src="assets/js/main.js"></script>
</body>
</html>

events/templates/events/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Real World Django</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!-- Project style -->
    <link href="assets/css/style.css" rel="stylesheet" type="text/css">
</head>
<body>

<!-- Start TOP_BAR -->
<div class="container-fluid bg-white py-3">
    <div class="row align-items-center justify-content-between">
        <div class="col-auto text-center ms-4">
            <h4>Real World Django</h4>
        </div>
        <div class="col-auto text-center me-4">
            <a href="#" class="btn btn-outline-primary">Войти</a>
            <a href="#" class="btn btn-primary">Регистрация</a>
        </div>
    </div>
</div>
<!-- End TOP_BAR -->

<!-- Start WRAPPER -->
<div class="container-fluid">
    <div class="row align-items-center justify-content-center"
         style="min-height: 450px; background-image: url(assets/images/background/bg-1.jpg)">
        <div class="col-auto">
            <h1 class="text-white shadow-lg rounded p-4" style="font-size: 4.3rem">Выбери свое событие</h1>
        </div>
    </div>
</div>
<!-- End WRAPPER -->

<!-- Start EVENTS -->
<div class="container-fluid bg-white py-5 my-5">
    <div class="py-5">
        <p class="h1 text-center">Самое <span class="text-info"><u>интересное</u></span></p>
        <div class="row row-cols-1 row-cols-lg-3 row-cols-xxl-4 justify-content-center g-4 mt-4">

            <!-- Start EVENT_ITEM -->
            <div class="col" data-test="event">
                <div class="card mb-3 h-100 shadow">
                    <div class="card-body">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="assets/images/svg-icon/watch.svg" alt="event" class="card-img">
                            </div>
                            <div class="col-md-8 ps-lg-3">
                                <h5 class="card-title">Шоу "Big Stand Up"</h5>
                                <p class="card-text">Потрясающее приключение «Big Stand Up» отвлечет от будней суеты и
                                    поможет окунутся в радость</p>
                                <p class="card-text">
                                    <small class="text-muted" data-test="event_start">
                                        1 января 2001
                                    </small>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="event_detail.html" class="btn btn-primary">Подробее</a>
                    </div>
                </div>
            </div>
            <!-- End EVENT_ITEM -->

            <!-- Start EVENT_ITEM -->
            <div class="col" data-test="event">
                <div class="card mb-3 h-100 shadow">
                    <div class="card-body">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="assets/images/svg-icon/household.svg" alt="event" class="card-img">
                            </div>
                            <div class="col-md-8 ps-lg-3">
                                <h5 class="card-title">Субботник "Под крышей дома моего"</h5>
                                <p class="card-text">Бери лопату и сделай свой двор чистым, а день незабываемо
                                    веселым!</p>
                                <p class="card-text">
                                    <small class="text-muted" data-test="event_start">
                                        1 февраля 2001
                                    </small>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="event_detail.html" class="btn btn-primary">Подробее</a>
                    </div>
                </div>
            </div>
            <!-- End EVENT_ITEM -->

            <!-- Start EVENT_ITEM -->
            <div class="col" data-test="event">
                <div class="card mb-3 h-100 shadow">
                    <div class="card-body">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="assets/images/svg-icon/delivery-man.svg" alt="event" class="card-img">
                            </div>
                            <div class="col-md-8 ps-lg-3">
                                <h5 class="card-title">Волонтерский проект "Delivery-бабушка"</h5>
                                <p class="card-text">Тянет на добрые дела? Хватай свою желтую термо-сумку и порадуй
                                    бабушку
                                    свежими пирожками из нашей кухни.</p>
                                <p class="card-text">
                                    <small class="text-muted" data-test="event_start">
                                        1 марта 2001
                                    </small>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="event_detail.html" class="btn btn-primary">Подробее</a>
                    </div>
                </div>
            </div>
            <!-- End EVENT_ITEM -->

        </div>
        <div class="text-center mt-5">
            <a href="event_list.html" class="btn btn-outline-primary">Смотреть все</a>
        </div>
    </div>
</div>
<!-- End EVENTS -->

<!-- Start REVIEWS -->
<div class="container-fluid bg-white py-5 my-5">
    <div class="py-5">
        <p class="h1 text-center">Отзывы</p>
        <div class="row row-cols-1 row-cols-lg-3 row-cols-xxl-4 justify-content-center g-4 mt-4">

            <!-- Start REVIEW_ITEM -->
            <div class="col" data-test="review">
                <div class="card rounded bg-light pt-4 h-100 text-center">
                    <img src="assets/images/svg-icon/rating.svg" class="card-img-top" alt="review"
                         style="max-height: 5rem">
                    <div class="card-body">
                        <p class="card-text" data-test="review_text">
                            Такое было крутое событие, ни разу не пожалел, что пошел. Извините,
                            конечно, но я хочу еще раз повторить!
                        </p>
                    </div>
                    <div class="card-footer text-center fw-bold">
                        Алексей Гуфаров
                    </div>
                </div>
            </div>
            <!-- End REVIEW_ITEM -->

            <!-- Start REVIEW_ITEM -->
            <div class="col" data-test="review">
                <div class="card rounded bg-light pt-4 h-100 text-center">
                    <img src="assets/images/svg-icon/rating.svg" class="card-img-top" alt="review"
                         style="max-height: 5rem">
                    <div class="card-body">
                        <p class="card-text" data-test="review_text">
                            Нормально так тусанули!
                        </p>
                    </div>
                    <div class="card-footer text-center fw-bold">
                        Андрей Жалелов
                    </div>
                </div>
            </div>
            <!-- End REVIEW_ITEM -->

            <!-- Start REVIEW_ITEM -->
            <div class="col" data-test="review">
                <div class="card rounded bg-light pt-4 h-100 text-center">
                    <img src="assets/images/svg-icon/rating.svg" class="card-img-top" alt="review"
                         style="max-height: 5rem">
                    <div class="card-body">
                        <p class="card-text" data-test="review_text">
                            Раньше все было как-то серо, а теперь у меня есть сотня другая
                            друзей-подруг, с которыми мы провели незабываемый поход!
                        </p>
                    </div>
                    <div class="card-footer text-center fw-bold">
                        Алеся Анохина
                    </div>
                </div>
            </div>
            <!-- End REVIEW_ITEM -->

        </div>
    </div>
</div>
<!-- End REVIEWS -->

<!-- Start FOOTER -->
<div class="container-fluid bg-white py-5 text-center">
    <p class="mb-0">© Pumpskill. Real World Django</p>
</div>
<!-- End FOOTER -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
<script src="assets/js/main.js"></script>
</body>
</html>